### ISSUE TITLE
{% blocktext %} tag does not observe default text

### ISSUE THREAD

**Issue by derek73** [antonagestam/django-text#65] opened 2016-03-26 05:40 UTC
The docs say the `{% blocktext %}` tag should allow for default text. This doesn't work for me.

```
    {% blocktext "content" %}
        Put your default text here!
    {% endblocktext %}
```

outputs:

```
content text
```

Once the text has been edited, it works as expected.

**Comment by antonagestam** [comment] 2016-03-26 06:15
Hmm, this is another one I can't reproduce. The tests should actually be covering this. Are you sure there wasn't another text node with the same name saved in your database with that content from earlier?

**Comment by derek73** [comment] 2016-03-26 06:22
I had just migrated the db, but I just tried getting a new db backup and rerunning the migrations to confirm and this time it worked. I initially got an error about a duplicate key from postgresql, then I refreshed the page and it worked. Strange.

**Comment by antonagestam** [comment] 2016-04-03 00:48
I'll go ahead and close this for now then.

**Closed as completed by antonagestam** 2016-04-03 00:48 UTC
